GET http://localhost:8080/posts
//get all

###
GET  http://localhost:8080/posts/1
//get by id

###
POST http://localhost:8080/posts 
Content-Type: application/json

{
    "titulo": "Backend",
    "texto": "Descrição 100",
    "userId": 1
}
###
PUT http://localhost:8080/posts?id=2 
Content-Type: application/json

{
    "titulo": "Backend 3",
    "texto": "Descrição 300"
}

###
DELETE  http://localhost:8080/posts?id=2 
Content-Type: application/json

{
    "titulo": "Backend 3",
    "texto": "Descrição 300"
}